# Generated by Django 5.2.7 on 2025-10-28 15:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('area_hectareas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('distrito', models.CharField(max_length=150)),
                ('departamento', models.CharField(max_length=150)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('cuit', models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT')),
                ('domicilio', models.CharField(max_length=300)),
                ('distrito', models.CharField(max_length=150)),
                ('localidad', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REGISTRADO', 'Registrado'), ('RENOVACION', 'Renovación'), ('TRANSFERENCIA', 'Transferencia')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Productor',
                'verbose_name_plural': 'Productores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoSenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion_oreja', models.CharField(choices=[('DERECHA', 'Oreja derecha'), ('IZQUIERDA', 'Oreja izquierda'), ('AMBAS', 'Ambas orejas')], max_length=20)),
                ('imagen_referencia', models.ImageField(blank=True, null=True, upload_to='referencias/')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=120)),
                ('objeto_id', models.CharField(max_length=120)),
                ('accion', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MarcaSenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.CharField(choices=[('NUEVA', 'Marca nueva'), ('RENOVACION', 'Renovación'), ('TRANSFERENCIA', 'Transferencia')], default='NUEVA', max_length=20)),
                ('numero_orden', models.PositiveIntegerField(unique=True, verbose_name='Número de orden')),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('descripcion_marca', models.TextField(verbose_name='Descripción de la marca')),
                ('imagen_marca', models.ImageField(blank=True, null=True, upload_to='marcas/')),
                ('descripcion_senal', models.TextField(blank=True, verbose_name='Descripción de la señal')),
                ('vacuno', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('caballar', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('mular', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('asnal', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ovino', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cabrio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_sellado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDA', 'Vencida'), ('BAJA', 'Baja'), ('EN_TRAMITE', 'En trámite')], default='EN_TRAMITE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('imagen_carnet_frente', models.ImageField(blank=True, null=True, upload_to='carnets/')),
                ('imagen_carnet_dorso', models.ImageField(blank=True, null=True, upload_to='carnets/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_senales', to='app_registros.campo')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_senales', to='app_registros.productor')),
                ('tipo_senal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_registros.tiposenal')),
            ],
            options={
                'verbose_name': 'Marca y Señal',
                'verbose_name_plural': 'Marcas y Señales',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.AddField(
            model_name='campo',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='app_registros.productor'),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.CharField(choices=[('NUEVO', 'Registro nuevo'), ('RENOVACION', 'Renovación'), ('TRANSFERENCIA', 'Transferencia'), ('BAJA', 'Baja')], max_length=20)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='solicitudes/')),
                ('observaciones', models.TextField(blank=True)),
                ('marca_senal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app_registros.marcasenal')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app_registros.productor')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('inspector', 'Inspector')], default='empleado', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
