# Generated by Django 5.2.7 on 2025-11-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='area_hectareas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='campo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='departamento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='provincia',
            field=models.CharField(default='Catamarca', max_length=150),
        ),
    ]
