# Generated by Django 5.2.7 on 2025-11-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0002_productor_area_hectareas_productor_campo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productor',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='productor',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='productor',
            name='calle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='localidad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
