# Generated by Django 5.2.7 on 2025-11-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0003_remove_productor_distrito_remove_productor_domicilio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenMarcaPredefinida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='marcas/predefinidas/')),
                ('tipo_marca', models.CharField(choices=[('FLANCO', 'Flanco'), ('ANCA', 'Anca'), ('COSTILLAR', 'Costillar'), ('PALETA', 'Paleta'), ('CUELLO', 'Cuello'), ('MEJILLA', 'Mejilla'), ('OTRO', 'Otro')], default='FLANCO', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Imagen de Marca Predefinida',
                'verbose_name_plural': 'Imágenes de Marcas Predefinidas',
            },
        ),
    ]
