# Generated by Django 5.2.7 on 2026-01-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0004_imagenmarcapredefinida'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcasenal',
            name='imagen_predefinida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_registros.imagenmarcapredefinida', verbose_name='Imagen predefinida'),
        ),
    ]
