# Generated by Django 5.2.7 on 2026-01-20 14:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0005_marcasenal_imagen_predefinida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_solicitud'], 'permissions': [('can_review_solicitud', 'Puede revisar solicitudes'), ('can_approve_solicitud', 'Puede aprobar solicitudes'), ('can_reject_solicitud', 'Puede rechazar solicitudes')], 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AddField(
            model_name='solicitud',
            name='aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='imagen_adicional_1',
            field=models.ImageField(blank=True, null=True, upload_to='solicitudes/imagenes/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='imagen_adicional_2',
            field=models.ImageField(blank=True, null=True, upload_to='solicitudes/imagenes/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='Motivo de la solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observaciones_internas',
            field=models.TextField(blank=True, verbose_name='Observaciones internas'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='marca_senal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='app_registros.marcasenal'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones generales'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_tramite',
            field=models.CharField(choices=[('NUEVO', 'Registro nuevo'), ('RENOVACION', 'Renovación'), ('TRANSFERENCIA', 'Transferencia'), ('BAJA', 'Baja'), ('MODIFICACION', 'Modificación')], max_length=20),
        ),
    ]
