# Generated by Django 5.2.7 on 2026-02-02 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0006_alter_solicitud_options_solicitud_aprobador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='solicitudes/documentos/%Y/%m/%d/')),
                ('tipo', models.CharField(choices=[('DNI', 'Documento de Identidad'), ('DOMICILIO', 'Constancia de Domicilio'), ('TITULO', 'Título de Propiedad'), ('CONTRATO', 'Contrato de Arrendamiento'), ('OTRO', 'Otro')], max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_registros.solicitud')),
                ('usuario_subida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlujoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.CharField(choices=[('NUEVA_MARCA', 'Nueva Marca'), ('RENOVACION', 'Renovación'), ('TRANSFERENCIA', 'Transferencia'), ('BAJA', 'Baja'), ('MODIFICACION', 'Modificación'), ('DUPLICADO', 'Duplicado de Carnet')], max_length=20)),
                ('estado_origen', models.CharField(max_length=50)),
                ('estado_destino', models.CharField(max_length=50)),
                ('rol_requerido', models.CharField(choices=[('SOLICITANTE', 'Solicitante'), ('EMPLEADO', 'Empleado'), ('ADMIN', 'Administrador'), ('INSPECTOR', 'Inspector')], max_length=20)),
                ('condiciones', models.JSONField(blank=True, default=dict)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo_tramite', 'orden'],
                'unique_together': {('tipo_tramite', 'estado_origen', 'estado_destino')},
            },
        ),
    ]
