# Generated by Django 5.2.7 on 2026-02-04 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0007_documentosolicitud_flujotramite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentosolicitud',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento de Solicitud', 'verbose_name_plural': 'Documentos de Solicitud'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_solicitud'], 'permissions': [('can_review_solicitud', 'Puede revisar solicitudes'), ('can_approve_solicitud', 'Puede aprobar solicitudes'), ('can_reject_solicitud', 'Puede rechazar solicitudes')]},
        ),
        migrations.RemoveField(
            model_name='documentosolicitud',
            name='tipo',
        ),
        migrations.AddField(
            model_name='documentosolicitud',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='documentosolicitud',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('CUIT', 'Constancia de CUIT'), ('DOMICILIO', 'Constancia de Domicilio'), ('TITULO', 'Título de Propiedad'), ('CONTRATO', 'Contrato de Arrendamiento'), ('PLANO', 'Plano del Campo'), ('FOTOGRAFIA', 'Fotografía de la Marca'), ('OTRO', 'Otro Documento')], default='OTRO', max_length=50, verbose_name='Tipo de Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cantidad_animales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='documentos_presentados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='documentos_requeridos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='numero_expediente',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Expediente'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observaciones_aprobacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observaciones_revision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitante_dni',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitante_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_ganado',
            field=models.CharField(choices=[('VACUNO', 'Vacuno'), ('EQUINO', 'Equino'), ('OVINO', 'Ovino'), ('CAPRINO', 'Caprino'), ('PORCINO', 'Porcino'), ('MIXTO', 'Mixto')], default='VACUNO', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosolicitud',
            name='archivo',
            field=models.FileField(upload_to='solicitudes/documentos/%Y/%m/%d/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentosolicitud',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida'),
        ),
        migrations.AlterField(
            model_name='documentosolicitud',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Documento'),
        ),
        migrations.AlterField(
            model_name='documentosolicitud',
            name='usuario_subida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Subió'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='observaciones_internas',
            field=models.TextField(blank=True),
        ),
    ]
