# Generated by Django 5.2.7 on 2026-02-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0008_alter_documentosolicitud_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcasenal',
            name='imagen_predefinida',
        ),
        migrations.AddField(
            model_name='marcasenal',
            name='imagenes_predefinidas',
            field=models.ManyToManyField(blank=True, help_text='Seleccione una o más imágenes que componen la marca', to='app_registros.imagenmarcapredefinida', verbose_name='Imágenes predefinidas'),
        ),
    ]
