# Generated by Django 5.2.7 on 2026-02-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0009_remove_marcasenal_imagen_predefinida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcasenal',
            name='numero_orden',
            field=models.PositiveIntegerField(editable=False, unique=True, verbose_name='Número de orden'),
        ),
    ]
