# Generated by Django 5.2.7 on 2026-07-27 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0011_add_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcasenal',
            name='camelidos',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='marcasenal',
            name='porcino',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='marcasenal',
            name='tipo_marca',
            field=models.CharField(blank=True, choices=[('DIBUJO', 'Dibujo'), ('INICIALES', 'Iniciales'), ('NUMEROS', 'Números'), ('LETRA_NUMERO', 'Letra y Número')], max_length=20, verbose_name='Tipo de Marca'),
        ),
        migrations.AlterField(
            model_name='marcasenal',
            name='tipo_tramite',
            field=models.CharField(choices=[('REGISTRO_MARCA_SENAL', 'Registro Marca y Señal'), ('REGISTRO_SENALES', 'Registro Señales solas')], default='NUEVA', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_ganado',
            field=models.CharField(choices=[('VACUNO', 'Vacuno'), ('EQUINO', 'Equino'), ('MULAR', 'Mular'), ('ASNAL', 'Asnal'), ('OVINO', 'Ovino'), ('CAPRINO', 'Caprino'), ('PORCINO', 'Porcino'), ('CAMELIDOS', 'Camélidos')], default='VACUNO', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_tramite',
            field=models.CharField(choices=[('RENOVACION', 'Renovación'), ('RENOVACION_TRANSFERENCIA', 'Renovación y Transferencia'), ('RENOVACION_MOD_SENALES', 'Renovación y Modificación de Señales'), ('TRANSFERENCIA_MOD_SENAL', 'Transferencia y Modificación de Señal'), ('DUPLICADO', 'Duplicado'), ('BAJA', 'Baja'), ('REGISTRO_MARCAS_SENALES', 'Registro Marcas y Señales'), ('REGISTRO_SENALES', 'Registro Señales')], max_length=30),
        ),
    ]
