# Generated by Django 5.2.7 on 2026-07-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0012_marcasenal_camelidos_marcasenal_porcino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcasenal',
            name='senales_orejeras',
            field=models.JSONField(blank=True, null=True, verbose_name='Señales Orejeras'),
        ),
    ]
