# Generated by Django 5.2.7 on 2026-08-05 13:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0013_marcasenal_senales_orejeras'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='poligono',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
