# Generated by Django 5.2.7 on 2026-08-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0014_campo_poligono'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='descripcion_marca_nueva',
            field=models.TextField(blank=True, verbose_name='Nueva descripción de marca'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='descripcion_senal_nueva',
            field=models.TextField(blank=True, verbose_name='Nueva descripción de señal'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='senales_orejeras_nuevas',
            field=models.JSONField(blank=True, null=True, verbose_name='Nuevas señales orejeras'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_marca_nueva',
            field=models.CharField(blank=True, choices=[('DIBUJO', 'Dibujo'), ('INICIALES', 'Iniciales'), ('NUMEROS', 'Números'), ('LETRA_NUMERO', 'Letra y Número')], max_length=20, verbose_name='Nuevo tipo de marca'),
        ),
    ]
